sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- yarn add polymer-cli -g
- polymer install --variants
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: Lqho2jdWYfRVeYswzah9jQCkm/gUoDEx1UTYPJmdobtH3GKdFcWm9Y1Yn5/1zTSWrSFFpxqEC94JYbZV1nRIdojIWFOdKbgc3HJgPa3lfKoyCFcxZ1cu/vPtn95s26tmImpoxTVjSFf94U5tkcXaceAJq/78Ou8pEDSoF0WslBFKq12+ysvvknDwlGS3vKp1FLS/ISGiNB3OoLrGgHdn/szdX+Z5Qww7FDiZ9n8xiPoYU1mn+igaR168BIifGcb1TzFGkunng32LKhp+kVv6a0GrWt6O5S/gFQO9Wt2nL9ItZlS3eP1GPfqVmS8mbhaXkByGzcuOpiq/u+nL96Cgv9/9PMIr2lDYY2g6lEpO382stqacF8G00OJgV1ZipLXgmQg7C3UjZ9vxvNvcYapdNOuqIa+tbVgyciEA7JlPYnc1gYDnJPWs0oL3L+kNakYjQjzsl9Ntg+lag+1lU0Bm4jHPg1csXXi1rEZqAN4DdOpEfKvOUEm2EFyseqXxVlVA3tBu6MQza09bBB/GHLXw4mJ3014Mftt0hvvbB0H2bza29LLryTQ5dS8GiaLWv07RCFr+uJlvhi9oGvRrpNbNpQ5U4qDpb8sve3JTOYznS6oyMcAATSehXM8lc3r6DAXwyhimilUg2VliwIed4znodLoSFrcTt0H/zSo/hjVSYpY=
  - secure: KzKQePdnrAPdG4xBLTwclwdBulVMGlA+/L8zXOfY0zpQAc8ORZ7n8sUKbV+bRqIQS3Cn8f4vTrpaaQ1RYfrdJ5tE6RcacsTFwP7RW2eHLEhO+tEL9v7CfJBwlXa/+2sZC5XpcOnchgX5SC3A3O709mb89XYxNRghUDibuwmr4oGKtE92PF8rIfQ+35OO/bcIN739S34I5ggJh/oUAVpC8KWufPPITWUnMfGxwbsKBuHcdE9QRs6kPAAVFpWPnm9rFHE51kA0ROty1Xyecfh2w8eH07Bi2zCwnVrRZEegl6G6ORVDZsv523AJPe5Q8Lvuvrpm0di4vfnv8ImlWU7aFb5UK+65vJfnIRNztzVkYO4IobX2TSeUseI3MTv43j6kn+ujvfHAyB38HZvtCmAW0JjLWP8shb/1fvHSa4gTjKnChQUQiUB8WVr4mUUdhuzB1nVk8jn3buVOv+1rVPpJDZmD0Iw1MkaUoeKaWXjLXPIx2E8k9a/CSwMVQ981DX93OpkjrLtaqgQfwEpHRpsXeBNSgpVqcbOJO4mThRvNdYbbESmeEFT+iTR7ddarwbwuJmbYs3QtZk3j2PHldfyTcqNRBT6NaaJZebVas7mtxF6AWaruHarcKPWWWvuJqpakezLci+MbuAOPRhi3bxBwL8SQtNBaQQrNjWVB89raGFw=
  - secure: xIJr7nbNXs4WPbT8D9wXAydQUOYa2nT+mmYCQsLqywkhLmLzH14TyPdlCxT2fpg5/g59op9tYN6VXqoDcKt0kk8GqgRdxBXIq0NqX4vCqb98mkFzZOdOh3HZEtsKcxTwxjFzzCI1jXjymwUgPrwx7l6k/Z+NT/2tZFAS4t5+Pmud7540BANFSyOW3cT+eXCD9BeuHHmI8qsrhqm6unT5ruHdoJzC4qWsf0jvK2O1Xy+Qm1CxJqvE1x8ICgmvK+Arhhx8wbvs9cU6BrwI/Vonj0sHLFJfOCka7Wv/8ufCvV+QHX32gNrRwKf1S9rd1ua3vBep6thRJ9DhikZuaP1OAC1XnrUa65NVcXslSEaeZmS1UCMecPWU9CKEhq06wU99+1HZrgVqo+hyZWJtibgiVr7SYI2ZgVDGDeLOscfWFPnFM6tZP1FOm5DrHAKLoVPXn2hfYxkSWUnrdaxzYxpywXWueCT7SWTy3QrrOdULtgXLqX9RJ6WXNOHVWs9GFAybNaM8/BdanRZqBVpa2ueLvx2RHeFSSx9n+88yJB01ivJfO1CIf1+0Wj4jZNoGNFKPTrOsXqSCPHxHBHmR98jySTaVISNZok4QjxfWiGDSaIHv5bta4d1cQDf0/SwQrZDu5dxeNuycXrrsPT8brK75DrhUTB3M0YI7afrmEAoscWE=
  - secure: umk+HKhwk1QVF718mrMb3KvAi/5DjkhPF86VDhMnsqBReq6TohM+J5T4SJCmAGtjDentxF29PekMil45i4cpjkQ10c84W/goLf4TyG3WwlFnSnfbw2w0nlwY8X3vpUKaPiMpahw8tyY6K4KPh7yGzvnVaqmFOE+7WQkwdIUlDdMe4LcKpyrrFyw7ZKZHalH1xQGdqdIGpmatExNfK2lsoSVgQwjyensxgo193UkQWPZ44Kpp9v7iqseziAyFN7f4Syl33FHwUv95snxEamdN88Rhzwqz+fy7hLjWvSTlw6r75F0nGgID+c+oiVnakVaytQOpOCixCKO47hA3laP3NWmGs8XqNf/V3f3179UXs0+L6QA8X0GqwfazQ8TJtVoBOOop79IniKdf6q/BvMBFfHJwm+7j8xC23qPw8RpfSW06z1dqCkjf6mnDTBPTIBe8VR/bTpgov7mluF/Q7hx2zWdwrwhA7km4Ck9PvGJ0K8DtywH4nzMchay3JxeHLC4V2yuyjFpadQRJiXTd33c4bDVWponWy509IiUN/cc5ay+Q7JpO6ygWQ84IhTtUnouyEsZIapxpwuIUMG57q1S9ZaAVWHvNZ4OQZfZjSAvcdan7XaIrlOTqY3aQg+f1rxrWhCUDaenp8Q1gqlRNj8zqwxZhZgWseyFckxXnVtytEzE=
